# Generated by Django 4.0.7 on 2022-09-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
