# Generated by Django 4.0.7 on 2022-09-13 17:48

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_queue_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=254)),
        ),
        migrations.AlterField(
            model_name='queue',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='queue',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='queue',
            name='notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True)),
        ),
        migrations.AlterField(
            model_name='queue',
            name='phone_number',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
